import web3 from './web3';

const address = process.env.REACT_APP_SMART_CONTRACT_PACKAGE_ADDRESS;

const abi = [{ inputs: [{ internalType: 'address', name: 'entity_contract', type: 'address' }], stateMutability: 'nonpayable', type: 'constructor' }, { anonymous: false, inputs: [{ indexed: true, internalType: 'address', name: 'previousAdmin', type: 'address' }, { indexed: true, internalType: 'address', name: 'newAdmin', type: 'address' }], name: 'SuperAdminTransferred', type: 'event' }, { inputs: [{ internalType: 'string', name: 'packageId', type: 'string' }, { internalType: 'string', name: '_entityId', type: 'string' }, { internalType: 'string', name: 'dataPackage', type: 'string' }], name: 'addPackage', outputs: [], stateMutability: 'nonpayable', type: 'function' }, { inputs: [], name: 'adminAddress', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' }, { inputs: [{ internalType: 'string', name: 'packageId', type: 'string' }], name: 'deletePackage', outputs: [], stateMutability: 'nonpayable', type: 'function' }, { inputs: [{ internalType: 'string', name: 'packageId', type: 'string' }, { internalType: 'string', name: 'dataPackage', type: 'string' }], name: 'editPackage', outputs: [], stateMutability: 'nonpayable', type: 'function' }, { inputs: [{ internalType: 'string', name: 'packageId', type: 'string' }], name: 'findPackageId', outputs: [{ internalType: 'string', name: '', type: 'string' }], stateMutability: 'view', type: 'function' }, { inputs: [{ internalType: 'string', name: '_packageId', type: 'string' }], name: 'getEntityIdByPackageId', outputs: [{ internalType: 'string', name: '', type: 'string' }], stateMutability: 'view', type: 'function' }, { inputs: [{ internalType: 'string', name: '_packageId', type: 'string' }], name: 'getPackageDetailById', outputs: [{ internalType: 'string', name: '', type: 'string' }, { internalType: 'string', name: '', type: 'string' }, { internalType: 'string', name: '', type: 'string' }, { internalType: 'string', name: '', type: 'string' }], stateMutability: 'view', type: 'function' }, { inputs: [{ internalType: 'address', name: 'newAdmin', type: 'address' }], name: 'transferAdmin', outputs: [], stateMutability: 'nonpayable', type: 'function' }]

const contract = web3 ? new web3.eth.Contract(abi, address) : null;

export default contract
