import web3 from './web3';

const address = process.env.REACT_APP_SMART_CONTRACT_USER_ADDRESS;

const abi = [{ anonymous: false, inputs: [{ indexed: true, internalType: 'address', name: 'previousAdmin', type: 'address' }, { indexed: true, internalType: 'address', name: 'newAdmin', type: 'address' }], name: 'SuperAdminTransferred', type: 'event' }, { inputs: [], name: 'adminAddress', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' }, { inputs: [{ internalType: 'uint256', name: 'user_id', type: 'uint256' }, { internalType: 'address', name: 'newPublicKey', type: 'address' }], name: 'changePublicKey', outputs: [{ internalType: 'bool', name: '', type: 'bool' }], stateMutability: 'nonpayable', type: 'function' }, { inputs: [], name: 'getListUser', outputs: [{ components: [{ internalType: 'address', name: 'public_key', type: 'address' }, { internalType: 'uint256', name: 'user_id', type: 'uint256' }, { internalType: 'string', name: 'username', type: 'string' }, { internalType: 'string', name: 'email', type: 'string' }], internalType: 'struct User.UserEntity[]', name: '', type: 'tuple[]' }], stateMutability: 'view', type: 'function' }, { inputs: [{ internalType: 'address', name: 'sender', type: 'address' }], name: 'getUserDetail', outputs: [{ internalType: 'address', name: '', type: 'address' }, { internalType: 'uint256', name: '', type: 'uint256' }, { internalType: 'string', name: '', type: 'string' }, { internalType: 'string', name: '', type: 'string' }], stateMutability: 'view', type: 'function' }, { inputs: [{ internalType: 'address', name: 'sender', type: 'address' }], name: 'getUserId', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' }, { inputs: [{ internalType: 'address', name: 'sender', type: 'address' }], name: 'getUsername', outputs: [{ internalType: 'string', name: '', type: 'string' }], stateMutability: 'view', type: 'function' }, { inputs: [{ internalType: 'uint256', name: 'user_id', type: 'uint256' }, { internalType: 'string', name: 'username', type: 'string' }, { internalType: 'string', name: 'email', type: 'string' }], name: 'signPublicKey', outputs: [], stateMutability: 'nonpayable', type: 'function' }, { inputs: [{ internalType: 'address', name: 'newAdmin', type: 'address' }], name: 'transferAdmin', outputs: [], stateMutability: 'nonpayable', type: 'function' }]

const contract = web3 ? new web3.eth.Contract(abi, address) : null;

export default contract
